spring:
  application:
    name: library-client
  profiles:
    active: resilience4j
  cloud:
    config:
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 4s


use: feign