spring:
  application:
    name: library-service
  datasource:
    url: jdbc:postgresql://localhost:5430/library
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    root: error
    org.springframework: error


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    defaults:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
#    instance-id: library-service:8082
    prefer-ip-address: true

#server.port: 8082