spring:
  datasource:
    url: jdbc:h2:mem:maindb
  liquibase:
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true

logging:
  level:
    root: error
    org.springframework: error

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true