spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    root: error
    org.springframework: error

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true