version: '3'
services:
  postgres_database:
    image: postgres:13
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

